In [7]:
import pandas as pd

# Define lists to store parsed data
discipline1_list = []
discipline2_list = []
score_list = []
discipline1_for_discipline1_list = []
discipline1_score = 0
# Open and read the file
with open('results_nn_100000.txt', 'r') as file:
    discipline1 = ''
    for line in file.readlines():
        if line.startswith('Discipline'):
            # Extract discipline1 and its score for this block
            discipline1 = line.split(':')[1].strip()
            if discipline1_score: 
                discipline1_for_discipline1_list.extend([discipline1_score for i in range(42)])
        elif line.startswith('  '):
            # Extract discipline2 and score
            parts = line.strip().split(': ')
            discipline2 = parts[0].strip()
            score = float(parts[1].strip())
            
            # Append the data to lists
            discipline1_list.append(discipline1)
            discipline2_list.append(discipline2)
            score_list.append(score)
            if discipline1 == discipline2: 
                discipline1_score = score
    discipline1_for_discipline1_list.extend([discipline1_score for i in range(42)])

# Create a DataFrame
df = pd.DataFrame({
    'Discipline1': discipline1_list,
    'Discipline2': discipline2_list,
    'Score': score_list,
    'Discipline1Value': discipline1_for_discipline1_list
})

# Display the first few rows of the DataFrame
print(df.head())

  Discipline1        Discipline2     Score  Discipline1Value
0  Psychology         Psychology  5.816016          5.816016
1  Psychology  Clinical medicine  4.003860          5.816016
2  Psychology    Health sciences  3.173861          5.816016
3  Psychology     Basic medicine  2.826011          5.816016
4  Psychology          Sociology  1.643970          5.816016

In [8]:
df

               Discipline1            Discipline2     Score  Discipline1Value
0               Psychology             Psychology  5.816016          5.816016
1               Psychology      Clinical medicine  4.003860          5.816016
2               Psychology        Health sciences  3.173861          5.816016
3               Psychology         Basic medicine  2.826011          5.816016
4               Psychology              Sociology  1.643970          5.816016
...                    ...                    ...       ...               ...
1759  Health biotechnology                History  0.001955          3.561095
1760  Health biotechnology            Archaeology  0.000978          3.561095
1761  Health biotechnology  Other social sciences  0.000978          3.561095
1762  Health biotechnology               Religion  0.000978          3.561095
1763  Health biotechnology       Other humanities  0.000000          3.561095

[1764 rows x 4 columns]

In [9]:
df.to_csv('data.csv', index=False)

In [10]:
import pandas as pd

# Load the DataFrame
df = pd.read_csv('data.csv')  # Make sure to adjust the path to your CSV file

# Initialize an empty list to store the final data
final_data = []

# Iterate over each unique discipline in Discipline1
for discipline in df['Discipline1'].unique():
    discipline_data = df[df['Discipline1'] == discipline]
    S = discipline_data['Discipline1Value'].iloc[0]

    # Calculations
    disciplines_greater_than_S_minus_1_list = discipline_data[discipline_data['Score'] > S - 1]
    disciplines_greater_than_S_minus_1 = len(disciplines_greater_than_S_minus_1_list)
    disciplines_score_above_1 = len(discipline_data[discipline_data['Score'] > 1])

    # Exclude the current discipline from the first 3 calculations
    if discipline in disciplines_greater_than_S_minus_1_list['Discipline2'].values:
        disciplines_greater_than_S_minus_1 -= 1
        disciplines_greater_than_S_minus_1_list = disciplines_greater_than_S_minus_1_list[disciplines_greater_than_S_minus_1_list['Discipline2'] != discipline]['Discipline2'].tolist()
    else:
        disciplines_greater_than_S_minus_1_list = disciplines_greater_than_S_minus_1_list['Discipline2'].tolist()

    rank_score_more_than_S_minus_1 = len(df[(df['Discipline2'] == discipline) & (df['Score'] > df['Discipline1Value'] - 1)])
    rank_score_more_than_S_minus_1_list = df[(df['Discipline2'] == discipline) & (df['Score'] > df['Discipline1Value'] - 1)].Discipline1.values
    rank_score_above_1 = len(df[(df['Discipline2'] == discipline) & (df['Score'] > 1)])

    final_data.append({
        'Discipline': discipline,
        'Disciplines > (S-1)': disciplines_greater_than_S_minus_1,
        'Disciplines with Score > 1': disciplines_score_above_1,
        'Nb of disciplines where this discipline is in the rank with score more than (S-1)': rank_score_more_than_S_minus_1,
        'Nb of disciplines where this discipline is in the ranking with score above 1': rank_score_above_1,
        'Disciplines List > (S-1)': disciplines_greater_than_S_minus_1_list,
        'Disciplines List score Sxa > Sx': rank_score_more_than_S_minus_1_list
    })

# Create a DataFrame from the final data list
final_df = pd.DataFrame(final_data)

# Display the DataFrame
final_df

,Discipline,Disciplines > (S-1),Disciplines with Score > 1,Nb of disciplines where this discipline is in the rank with score more than (S-1),Nb of disciplines where this discipline is in the ranking with score above 1,Disciplines List > (S-1),Disciplines List score Sxa > Sx
0,Psychology,0,7,12,19,[],"[Psychology, History, Sociology, Languages and..."
1,Educational sciences,0,8,5,4,[],"[Educational sciences, History, Art (arts, his..."
2,Health sciences,1,6,7,23,[Clinical medicine],"[Health sciences, History, Other social scienc..."
3,Other engineering and technologies,0,10,4,19,[],"[Other engineering and technologies, Art (arts..."
4,Chemical sciences,0,10,8,17,[],"[Chemical sciences, Chemical engineering, Nano..."
5,Environmental engineering,0,11,5,14,[],"[Environmental engineering, Chemical engineeri..."
6,Earth and related environmental sciences,0,11,8,19,[],"[Earth and related environmental sciences, Soc..."
7,History,9,7,4,4,"[Sociology, Economics and business, Psychology...","[History, Art (arts, history of arts, performi..."
8,"Agriculture, forestry, and fisheries",1,5,4,7,[Biological sciences],"[Agriculture, forestry, and fisheries, Other h..."
9,Biological sciences,0,8,12,17,[],"[Agriculture, forestry, and fisheries, Biologi..."
10,Computer and information sciences,1,6,6,13,"[Electrical engineering, electronic engineerin...","[Computer and information sciences, Art (arts,..."
11,Basic medicine,1,6,5,14,[Clinical medicine],"[Basic medicine, Art (arts, history of arts, p..."
12,Sociology,1,7,10,17,[Psychology],"[History, Sociology, Other social sciences, Ar..."
13,Languages and linguistics,1,7,3,2,[Psychology],"[Languages and linguistics, Other humanities, ..."
14,Social and economic geography,2,9,6,12,"[Earth and related environmental sciences, Eco...","[History, Social and economic geography, Other..."
15,Chemical engineering,2,8,3,7,"[Environmental engineering, Chemical sciences]","[Chemical engineering, Other humanities, Other..."
16,Clinical medicine,0,5,10,18,[],"[Health sciences, History, Basic medicine, Cli..."
17,"Electrical engineering, electronic engineering...",0,8,6,11,[],"[Computer and information sciences, Electrical..."
18,Political Science,1,7,5,5,[Economics and business],"[History, Political Science, Art (arts, histor..."
19,Other social sciences,6,7,3,1,"[Economics and business, Social and economic g...","[Other social sciences, Other humanities, Lite..."
20,Nano-technology,3,5,2,6,"[Chemical sciences, Materials engineering, Phy...","[Nano-technology, Other humanities]"
21,Physical sciences,2,9,4,11,"[Chemical sciences, Materials engineering]","[Nano-technology, Physical sciences, Other hum..."
22,Materials engineering,0,10,6,11,[],"[Nano-technology, Physical sciences, Materials..."
23,Civil engineering,0,10,3,6,[],"[Civil engineering, Other humanities, Literature]"
24,Mechanical engineering,0,12,3,11,[],"[Mechanical engineering, Other humanities, Lit..."
25,Economics and business,0,10,10,20,[],"[History, Social and economic geography, Polit..."
26,"Art (arts, history of arts, performing arts, m...",17,9,3,1,"[Psychology, Sociology, Social and economic ge...","[Art (arts, history of arts, performing arts, ..."
27,Religion,2,8,3,1,"[Sociology, Psychology]","[Religion, Other humanities, Literature]"
28,Philosophy and ethics,2,8,5,2,"[Psychology, Economics and business]","[History, Art (arts, history of arts, performi..."
29,Law,2,9,3,1,"[Sociology, Psychology]","[Law, Other humanities, Literature]"
30,Media and communications,5,8,4,1,"[Economics and business, Psychology, Computer ...","[Art (arts, history of arts, performing arts, ..."
31,Animal and dairy science,1,8,2,2,[Biological sciences],"[Animal and dairy science, Other humanities]"
32,Industrial Biotechnology,3,9,2,2,"[Chemical sciences, Materials engineering, Cli...","[Industrial Biotechnology, Other humanities]"
33,Medical engineering,4,11,2,2,"[Clinical medicine, Computer and information s...","[Medical engineering, Other humanities]"
34,Other humanities,41,7,2,0,"[Sociology, Psychology, Social and economic ge...","[Other humanities, Literature]"
35,Veterinary science,1,8,2,2,[Biological sciences],"[Other humanities, Veterinary science]"
36,Literature,32,8,2,1,"[Sociology, Psychology, History, Social and ec...","[Other humanities, Literature]"
37,Mathematics,0,6,3,7,[],"[Other humanities, Literature, Mathematics]"
38,Environmental biotechnology,1,8,3,3,[Biological sciences],"[Other humanities, Environmental biotechnology..."
39,Archaeology,3,5,3,1,"[Earth and related environmental sciences, Soc...","[Other humanities, Literature, Archaeology]"
40,Other agricultural sciences,7,10,2,1,"[Earth and related environmental sciences, Env...","[Other humanities, Other agricultural sciences]"
41,Health biotechnology,3,5,2,1,"[Biological sciences, Clinical medicine, Basic...","[Other humanities, Health biotechnology]"

In [11]:
final_df.to_csv('info_table.csv', index=False)

In [12]:
report = pd.read_csv('BERT-SVM/100000/ssci-scibert.txt', sep='    ')

<ipython-input-12-8d133b83d432>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  report = pd.read_csv('BERT-SVM/100000/ssci-scibert.txt', sep='    ')

In [13]:
report.columns = [x.strip() for x in report.columns]

In [16]:
report.rename(columns={'discipline': 'Discipline'}, inplace=True)

In [17]:
merged_df = pd.merge(report, final_df, on='Discipline', how='inner')

# Calculate correlation between 'Metric1' and 'Metric2'
correlation = merged_df[['Disciplines > (S-1)', 'recall']].corr()

print(correlation)

                     Disciplines > (S-1)    recall
Disciplines > (S-1)             1.000000 -0.827768
recall                         -0.827768  1.000000

In [18]:
merged_df.columns

Index(['Discipline', 'precision', 'recall', 'f1-score', 'support',
       'Disciplines > (S-1)', 'Disciplines with Score > 1',
       'Nb of disciplines where this discipline is in the rank with score more than (S-1)',
       'Nb of disciplines where this discipline is in the ranking with score above 1',
       'Disciplines List > (S-1)', 'Disciplines List score Sxa > Sx'],
      dtype='object')

In [19]:
merged_df[['Nb of disciplines where this discipline is in the rank with score more than (S-1)', 'recall']].corr()

,Nb of disciplines where this discipline is in the rank with score more than (S-1),recall
Nb of disciplines where this discipline is in the rank with score more than (S-1),1.000000,0.428663
recall,0.428663,1.000000

In [37]:
merged_df[['Nb of disciplines where this discipline is in the ranking with score above 1', 'recall']].corr()

,Nb of disciplines where this discipline is in the ranking with score above 1,recall
Nb of disciplines where this discipline is in the ranking with score above 1,1.000000,0.557712
recall,0.557712,1.000000

In [40]:
merged_df

,Discipline,precision,recall,f1-score,support,Disciplines > (S-1),Disciplines with Score > 1,Nb of disciplines where this discipline is in the rank with score more than (S-1),Nb of disciplines where this discipline is in the ranking with score above 1,Disciplines List > (S-1)
0,"Agriculture, forestry, and fisheries",0.6067,0.8249,0.6991,12129,1,5,4,7,[Biological sciences]
1,Animal and dairy science,0.7093,0.8005,0.7522,2000,1,8,2,2,[Biological sciences]
2,Archaeology,0.6462,0.7759,0.7051,638,3,5,3,1,"[Earth and related environmental sciences, Soc..."
3,"Art (arts, history of arts, performing arts, m...",0.6908,0.3404,0.4560,1234,17,9,3,1,"[Psychology, Sociology, Social and economic ge..."
4,Basic medicine,0.6769,0.8356,0.7479,72039,1,6,5,14,[Clinical medicine]
5,Biological sciences,0.8594,0.8513,0.8553,102494,0,8,12,17,[]
6,Chemical engineering,0.6521,0.7667,0.7048,13813,2,8,3,7,"[Environmental engineering, Chemical sciences]"
7,Chemical sciences,0.8649,0.8838,0.8742,77864,0,10,8,17,[]
8,Civil engineering,0.7482,0.7919,0.7694,14688,0,10,3,6,[]
9,Clinical medicine,0.9104,0.9316,0.9209,125697,0,5,10,18,[]
10,Computer and information sciences,0.7919,0.8032,0.7975,35393,1,6,6,13,"[Electrical engineering, electronic engineerin..."
11,Earth and related environmental sciences,0.8631,0.8155,0.8386,57881,0,11,8,19,[]
12,Economics and business,0.8508,0.8156,0.8328,25366,0,10,10,20,[]
13,Educational sciences,0.7678,0.8074,0.7871,7171,0,8,5,4,[]
14,"Electrical engineering, electronic engineering...",0.8338,0.8760,0.8544,38592,0,8,6,11,[]
15,Environmental biotechnology,0.5371,0.6358,0.5823,7030,1,8,3,3,[Biological sciences]
16,Environmental engineering,0.7647,0.8123,0.7878,39923,0,11,5,14,[]
17,Health biotechnology,0.3120,0.5585,0.4004,376,3,5,2,1,"[Biological sciences, Clinical medicine, Basic..."
18,Health sciences,0.6925,0.8521,0.7640,52566,1,6,7,23,[Clinical medicine]
19,History,0.6792,0.5323,0.5968,2168,9,7,4,4,"[Sociology, Economics and business, Psychology..."
20,Industrial Biotechnology,0.4891,0.6974,0.5750,1702,3,9,2,2,"[Chemical sciences, Materials engineering, Cli..."
21,Languages and linguistics,0.7167,0.7542,0.7350,3190,1,7,3,2,[Psychology]
22,Law,0.7535,0.6845,0.7173,2117,2,9,3,1,"[Sociology, Psychology]"
23,Literature,0.6991,0.4955,0.5800,783,32,8,2,1,"[Sociology, Psychology, History, Social and ec..."
24,Materials engineering,0.8673,0.8658,0.8665,55373,0,10,6,11,[]
25,Mathematics,0.7859,0.7921,0.7890,22052,0,6,3,7,[]
26,Mechanical engineering,0.7351,0.7672,0.7508,25287,0,12,3,11,[]
27,Media and communications,0.6946,0.5403,0.6078,3611,5,8,4,1,"[Economics and business, Psychology, Computer ..."
28,Medical engineering,0.4745,0.6488,0.5481,3984,4,11,2,2,"[Clinical medicine, Computer and information s..."
29,Nano-technology,0.4986,0.8300,0.6229,17390,3,5,2,6,"[Chemical sciences, Materials engineering, Phy..."
30,Other agricultural sciences,0.5367,0.4963,0.5157,1501,7,10,2,1,"[Earth and related environmental sciences, Env..."
31,Other engineering and technologies,0.6587,0.6918,0.6749,33808,0,10,4,19,[]
32,Other humanities,0.0000,0.0000,0.0000,500,41,7,2,0,"[Sociology, Psychology, Social and economic ge..."
33,Other social sciences,0.7547,0.5695,0.6492,2302,6,7,3,1,"[Economics and business, Social and economic g..."
34,Philosophy and ethics,0.7235,0.6653,0.6932,2124,2,8,5,2,"[Psychology, Economics and business]"
35,Physical sciences,0.8581,0.8158,0.8364,61304,2,9,4,11,"[Chemical sciences, Materials engineering]"
36,Political Science,0.7411,0.7262,0.7336,4825,1,7,5,5,[Economics and business]
37,Psychology,0.7858,0.7776,0.7817,26081,0,7,12,19,[]
38,Religion,0.6181,0.5923,0.6049,601,2,8,3,1,"[Sociology, Psychology]"
39,Social and economic geography,0.7378,0.6722,0.7035,12512,2,9,6,12,"[Earth and related environmental sciences, Eco..."
40,Sociology,0.6957,0.6636,0.6793,14140,1,7,10,17,[Psychology]
41,Veterinary science,0.6630,0.7886,0.7204,3476,1,8,2,2,[Biological sciences]

In [50]:
final_df

,Discipline,Disciplines > (S-1),Disciplines with Score > 1,Nb of disciplines where this discipline is in the rank with score more than (S-1),Nb of disciplines where this discipline is in the ranking with score above 1,Disciplines List > (S-1),Disciplines List score Sxa > Sx
0,Psychology,0,7,12,19,[],"[Psychology, History, Sociology, Languages and..."
1,Educational sciences,0,8,5,4,[],"[Educational sciences, History, Art (arts, his..."
2,Health sciences,1,6,7,23,[Clinical medicine],"[Health sciences, History, Other social scienc..."
3,Other engineering and technologies,0,10,4,19,[],"[Other engineering and technologies, Art (arts..."
4,Chemical sciences,0,10,8,17,[],"[Chemical sciences, Chemical engineering, Nano..."
5,Environmental engineering,0,11,5,14,[],"[Environmental engineering, Chemical engineeri..."
6,Earth and related environmental sciences,0,11,8,19,[],"[Earth and related environmental sciences, Soc..."
7,History,9,7,4,4,"[Sociology, Economics and business, Psychology...","[History, Art (arts, history of arts, performi..."
8,"Agriculture, forestry, and fisheries",1,5,4,7,[Biological sciences],"[Agriculture, forestry, and fisheries, Other h..."
9,Biological sciences,0,8,12,17,[],"[Agriculture, forestry, and fisheries, Biologi..."
10,Computer and information sciences,1,6,6,13,"[Electrical engineering, electronic engineerin...","[Computer and information sciences, Art (arts,..."
11,Basic medicine,1,6,5,14,[Clinical medicine],"[Basic medicine, Art (arts, history of arts, p..."
12,Sociology,1,7,10,17,[Psychology],"[History, Sociology, Other social sciences, Ar..."
13,Languages and linguistics,1,7,3,2,[Psychology],"[Languages and linguistics, Other humanities, ..."
14,Social and economic geography,2,9,6,12,"[Earth and related environmental sciences, Eco...","[History, Social and economic geography, Other..."
15,Chemical engineering,2,8,3,7,"[Environmental engineering, Chemical sciences]","[Chemical engineering, Other humanities, Other..."
16,Clinical medicine,0,5,10,18,[],"[Health sciences, History, Basic medicine, Cli..."
17,"Electrical engineering, electronic engineering...",0,8,6,11,[],"[Computer and information sciences, Electrical..."
18,Political Science,1,7,5,5,[Economics and business],"[History, Political Science, Art (arts, histor..."
19,Other social sciences,6,7,3,1,"[Economics and business, Social and economic g...","[Other social sciences, Other humanities, Lite..."
20,Nano-technology,3,5,2,6,"[Chemical sciences, Materials engineering, Phy...","[Nano-technology, Other humanities]"
21,Physical sciences,2,9,4,11,"[Chemical sciences, Materials engineering]","[Nano-technology, Physical sciences, Other hum..."
22,Materials engineering,0,10,6,11,[],"[Nano-technology, Physical sciences, Materials..."
23,Civil engineering,0,10,3,6,[],"[Civil engineering, Other humanities, Literature]"
24,Mechanical engineering,0,12,3,11,[],"[Mechanical engineering, Other humanities, Lit..."
25,Economics and business,0,10,10,20,[],"[History, Social and economic geography, Polit..."
26,"Art (arts, history of arts, performing arts, m...",17,9,3,1,"[Psychology, Sociology, Social and economic ge...","[Art (arts, history of arts, performing arts, ..."
27,Religion,2,8,3,1,"[Sociology, Psychology]","[Religion, Other humanities, Literature]"
28,Philosophy and ethics,2,8,5,2,"[Psychology, Economics and business]","[History, Art (arts, history of arts, performi..."
29,Law,2,9,3,1,"[Sociology, Psychology]","[Law, Other humanities, Literature]"
30,Media and communications,5,8,4,1,"[Economics and business, Psychology, Computer ...","[Art (arts, history of arts, performing arts, ..."
31,Animal and dairy science,1,8,2,2,[Biological sciences],"[Animal and dairy science, Other humanities]"
32,Industrial Biotechnology,3,9,2,2,"[Chemical sciences, Materials engineering, Cli...","[Industrial Biotechnology, Other humanities]"
33,Medical engineering,4,11,2,2,"[Clinical medicine, Computer and information s...","[Medical engineering, Other humanities]"
34,Other humanities,41,7,2,0,"[Sociology, Psychology, Social and economic ge...","[Other humanities, Literature]"
35,Veterinary science,1,8,2,2,[Biological sciences],"[Other humanities, Veterinary science]"
36,Literature,32,8,2,1,"[Sociology, Psychology, History, Social and ec...","[Other humanities, Literature]"
37,Mathematics,0,6,3,7,[],"[Other humanities, Literature, Mathematics]"
38,Environmental biotechnology,1,8,3,3,[Biological sciences],"[Other humanities, Environmental biotechnology..."
39,Archaeology,3,5,3,1,"[Earth and related environmental sciences, Soc...","[Other humanities, Literature, Archaeology]"
40,Other agricultural sciences,7,10,2,1,"[Earth and related environmental sciences, Env...","[Other humanities, Other agricultural sciences]"
41,Health biotechnology,3,5,2,1,"[Biological sciences, Clinical medicine, Basic...","[Other humanities, Health biotechnology]"

In [43]:
final_df['Nb of disciplines where this discipline is in the rank with score more than (S-1)'].value_counts()

Nb of disciplines where this discipline is in the rank with score more than (S-1)
3     11
2      9
5      5
4      5
6      4
10     3
12     2
8      2
7      1
Name: count, dtype: int64

In [64]:
final_df[final_df.Discipline == "Chemical sciences"]["Disciplines List score Sxa > Sx"].values

array([array(['Chemical sciences', 'Chemical engineering', 'Nano-technology',
              'Physical sciences', 'Industrial Biotechnology',
              'Other humanities', 'Literature', 'Other agricultural sciences'],
             dtype=object)                                                     ],
      dtype=object)

In [69]:
sorted(final_df.Discipline.values)

['Agriculture, forestry, and fisheries',
 'Animal and dairy science',
 'Archaeology',
 'Art (arts, history of arts, performing arts, music)',
 'Basic medicine',
 'Biological sciences',
 'Chemical engineering',
 'Chemical sciences',
 'Civil engineering',
 'Clinical medicine',
 'Computer and information sciences',
 'Earth and related environmental sciences',
 'Economics and business',
 'Educational sciences',
 'Electrical engineering, electronic engineering, information engineering',
 'Environmental biotechnology',
 'Environmental engineering',
 'Health biotechnology',
 'Health sciences',
 'History',
 'Industrial Biotechnology',
 'Languages and linguistics',
 'Law',
 'Literature',
 'Materials engineering',
 'Mathematics',
 'Mechanical engineering',
 'Media and communications',
 'Medical engineering',
 'Nano-technology',
 'Other agricultural sciences',
 'Other engineering and technologies',
 'Other humanities',
 'Other social sciences',
 'Philosophy and ethics',
 'Physical sciences',
 'Political Science',
 'Psychology',
 'Religion',
 'Social and economic geography',
 'Sociology',
 'Veterinary science']